# Generated by Django 4.1.7 on 2023-03-25 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=250)),
                ('password', models.CharField(max_length=250)),
                ('mobile', models.CharField(max_length=250)),
                ('fathername', models.CharField(max_length=250)),
                ('aadharno', models.CharField(max_length=250)),
            ],
        ),
    ]
