# Generated by Django 4.1.7 on 2023-03-25 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=250)),
                ('password', models.CharField(max_length=250)),
                ('mobile', models.CharField(max_length=250)),
                ('fathername', models.CharField(max_length=250)),
                ('aadharno', models.CharField(max_length=250)),
                ('roll_id', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
