# Generated by Django 4.1.7 on 2023-03-25 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0003_users_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='aadharno',
            field=models.CharField(default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='fathername',
            field=models.CharField(default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='mobile',
            field=models.CharField(default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.CharField(default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='roll_id',
            field=models.CharField(default=None, max_length=250, null=True),
        ),
    ]
