# Generated by Django 4.1.7 on 2023-03-28 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0011_delete_notification_delete_qualityparam_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
