# Generated by Django 4.1.7 on 2023-03-28 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0013_notification'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notification',
            new_name='Notifications',
        ),
    ]
