# Generated by Django 4.1.7 on 2023-03-28 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0015_qualityparam_transactionhistory'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='users',
            table='users',
        ),
    ]
