# Generated by Django 4.1.7 on 2023-03-28 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0016_alter_users_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(default=None, max_length=250, null=True)),
                ('name', models.CharField(default=None, max_length=250, null=True)),
                ('email', models.CharField(default=None, max_length=250, null=True)),
                ('password', models.CharField(default=None, max_length=250, null=True)),
                ('status', models.CharField(default=None, max_length=250, null=True)),
            ],
            options={
                'db_table': 'admin',
            },
        ),
    ]
