# Generated by Django 4.1.7 on 2023-03-28 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0019_auction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quaitytestuser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('userid', models.CharField(default=None, max_length=250, null=True)),
                ('productid', models.CharField(default=None, max_length=250, null=True)),
                ('certificateno', models.CharField(default=None, max_length=250, null=True)),
                ('datetime', models.CharField(default=None, max_length=250, null=True)),
                ('status', models.CharField(default=None, max_length=250, null=True)),
            ],
            options={
                'db_table': 'qualitytestuser',
            },
        ),
    ]
