# Generated by Django 4.1.7 on 2023-03-28 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0021_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='name',
        ),
    ]
