# Generated by Django 4.1.7 on 2023-03-28 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0022_remove_admin_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='phone',
            field=models.CharField(default=None, max_length=250, null=True),
        ),
    ]
