# Generated by Django 4.1.7 on 2023-03-29 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0023_admin_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='crops',
            name='image',
            field=models.FileField(default=None, max_length=500, null=True, upload_to='crop/'),
        ),
    ]
