# Generated by Django 4.1.7 on 2023-03-30 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0025_product_image_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='roleid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='admins.roles'),
        ),
    ]
