# Generated by Django 4.1.7 on 2023-03-30 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0026_product_roleid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(default=None, max_length=500, null=True, upload_to='product/'),
        ),
    ]
