# Generated by Django 4.1.7 on 2023-03-30 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0027_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='roleid',
        ),
    ]
