# Generated by Django 4.1.7 on 2023-04-04 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0029_product_roleid'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='image',
            field=models.FileField(default=None, max_length=500, null=True, upload_to='profile/'),
        ),
    ]
