# Generated by Django 4.1.7 on 2023-04-05 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0031_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='privacypolicy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('privacy', models.CharField(default=None, max_length=15000, null=True)),
            ],
        ),
    ]
