# Generated by Django 4.1.7 on 2023-04-05 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0033_termcondition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termcondition',
            name='terms',
            field=models.CharField(default=None, max_length=16000, null=True),
        ),
    ]
