# Generated by Django 4.1.7 on 2023-04-05 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0034_alter_termcondition_terms'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('about', models.CharField(default=None, max_length=16200, null=True)),
            ],
        ),
    ]
