# Generated by Django 4.1.7 on 2023-04-07 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0035_aboutus'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='company_favicon',
            field=models.FileField(default=None, max_length=500, null=True, upload_to='settings/favicon/'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='company_logo',
            field=models.FileField(default=None, max_length=500, null=True, upload_to='settings/logo/'),
        ),
    ]
