# Generated by Django 4.1.7 on 2023-04-11 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0037_users_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.CharField(default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='discounted_price',
            field=models.CharField(default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_discount',
            field=models.CharField(default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='stoct',
            field=models.CharField(default=None, max_length=250, null=True),
        ),
    ]
