# Generated by Django 4.1.7 on 2023-04-15 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0043_buyeroffers_farmeroffer_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyeroffers',
            old_name='farmeroffer_id',
            new_name='farmoffer_id',
        ),
    ]
