# Generated by Django 4.1.7 on 2023-04-15 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0044_rename_farmeroffer_id_buyeroffers_farmoffer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmeroffers',
            name='totalamount',
            field=models.CharField(default=None, max_length=250, null=True),
        ),
    ]
