# Generated by Django 4.1.7 on 2023-04-17 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0046_transactions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logisticsoffers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('offerdate', models.CharField(default=None, max_length=250, null=True)),
                ('traveldate', models.CharField(default=None, max_length=250, null=True)),
                ('price', models.CharField(default=None, max_length=250, null=True)),
                ('source_location', models.CharField(default=None, max_length=250, null=True)),
                ('destination_location', models.CharField(default=None, max_length=250, null=True)),
                ('offerstatus', models.CharField(default=None, max_length=250, null=True)),
                ('farmoffer_id', models.CharField(default=None, max_length=250, null=True)),
                ('logistics_id', models.CharField(default=None, max_length=250, null=True)),
            ],
            options={
                'db_table': 'offers_logistics',
            },
        ),
        migrations.AlterModelTable(
            name='buyeroffers',
            table='offers_buyer',
        ),
        migrations.AlterModelTable(
            name='farmeroffers',
            table='offers_farmer',
        ),
    ]
