# Generated by Django 4.1.7 on 2023-04-17 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0047_logisticsoffers_alter_buyeroffers_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logisticsoffers',
            name='quantity',
            field=models.CharField(default=None, max_length=250, null=True),
        ),
    ]
