# Generated by Django 4.1.7 on 2023-04-26 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0049_document'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='document',
            table='document',
        ),
    ]
