# Generated by Django 4.1.7 on 2023-04-27 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0050_alter_document_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldIssue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('farmerid', models.CharField(default=None, max_length=250, null=True)),
                ('location', models.CharField(default=None, max_length=250, null=True)),
                ('images', models.FileField(default=None, max_length=500, null=True, upload_to='fieldissue/')),
            ],
            options={
                'db_table': 'fieldissue',
            },
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
