# Generated by Django 4.1.7 on 2023-05-11 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0053_alter_farmeroffers_productid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmeroffers',
            name='productid',
            field=models.CharField(default=None, max_length=250, null=True),
        ),
    ]
