# Generated by Django 4.1.7 on 2023-05-11 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0055_abcd'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='abcd',
            table='demoabcd',
        ),
    ]
