# Generated by Django 4.1.7 on 2023-05-12 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0057_remove_farmeroffers_productid_farmeroffers_roleid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farmeroffers',
            old_name='roleid',
            new_name='productid',
        ),
    ]
