# Generated by Django 4.1.7 on 2023-05-12 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0058_rename_roleid_farmeroffers_productid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyeroffers',
            name='farmoffer_id',
        ),
        migrations.RemoveField(
            model_name='buyeroffers',
            name='productid',
        ),
        migrations.AddField(
            model_name='buyeroffers',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='admins.product'),
        ),
    ]
