# Generated by Django 4.1.7 on 2023-05-13 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0059_remove_buyeroffers_farmoffer_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quaitytestuser',
            old_name='certificateno',
            new_name='Certificateid',
        ),
        migrations.RenameField(
            model_name='quaitytestuser',
            old_name='datetime',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='quaitytestuser',
            name='productid',
        ),
        migrations.RemoveField(
            model_name='quaitytestuser',
            name='userid',
        ),
        migrations.AddField(
            model_name='quaitytestuser',
            name='certificateimage',
            field=models.FileField(default=None, max_length=500, null=True, upload_to='fieldissue/certificate'),
        ),
        migrations.AddField(
            model_name='quaitytestuser',
            name='farmer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='admins.users'),
        ),
        migrations.AddField(
            model_name='quaitytestuser',
            name='images',
            field=models.FileField(default=None, max_length=500, null=True, upload_to='fieldissue/'),
        ),
        migrations.AddField(
            model_name='quaitytestuser',
            name='multipleimages',
            field=models.FileField(default=None, max_length=500, null=True, upload_to='fieldissue/multi'),
        ),
    ]
