# Generated by Django 4.1.7 on 2023-05-13 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0060_rename_certificateno_quaitytestuser_certificateid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quaitytestuser',
            name='farmer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='farmer_id', to='admins.users'),
        ),
    ]
