# Generated by Django 4.1.7 on 2023-05-13 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0061_alter_quaitytestuser_farmer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quaitytestuser',
            name='farmer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='farmers', to='admins.users'),
        ),
    ]
